created module Arima filter_five_end.pl
sanger-tol/nf-core-modules pull request #2
Opened 2022-02-12 15:11 UTC by cibinsb

## PR checklist

Closes #XXX 

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, include test data in your PR.
- [x] Remove all TODO statements.
- [x] Emit the `versions.yml` file.
- [x] Follow the naming conventions.
- [x] Follow the parameters requirements.
- [x] Follow the input/output options guidelines.
- [x] Add a resource `label`
- [x] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
    - [x] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd`
    - [x] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd`

2022-02-17 13:29 UTC, muffato requested changes
Some changes to make this module consistent with the other Arima one

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +
Since we realised our Perl scripts are different from upstream, we shouldn't give reuse the commit IDs from arima
```suggestion
```

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +
Define it here like in `arima/2readsbamcombiner`
```suggestion

    def version = '0.001'

```

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +        'gitlab-registry.internal.sanger.ac.uk/tol-it/arima:v0.001' }"
```suggestion
    container "gitlab-registry.internal.sanger.ac.uk/tol-it/arima:${version}"
```

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/meta.yml
> +      licence:
```suggestion
      licence: MIT
```

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/meta.yml
> +      doi: ""
Can we remove this ? i.e. would it still pass the linters ?
```suggestion
```

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/meta.yml
> +      description: A wrapper tool around Arima Genomics's filter_five_end.pl to filter BAN files.
```suggestion
      description: A wrapper tool around Arima Genomics's filter_five_end.pl to filter BAM files.
```

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/meta.yml
> +      documentation: https://usermanual.wiki/Document/ArimaMappingUserGuideA160156v01.424413804/view
Do you know if this file was uploaded by Arima themselves ? If you're not sure, better to use the version that is on their GitHub
```suggestion
      documentation: https://github.com/ArimaGenomics/mapping_pipeline/blob/master/Arima_Mapping_UserGuide_A160156_v02.pdf
```

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +        filterfiveends: ${VERSION}
```suggestion
        samtools: \$(echo \$(samtools --version 2>&1) | sed 's/^.*samtools //; s/Using.*\$//' )
        arima: $version
```

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +    if (meta.single_end) {
It's the same command run twice on the `*1.bam` and `*2.bam` files, so my question is: is the best practice to do like this, or to limit this module to just 1 bam file and let the workflow connect the module to one or two files depending on the context ? (@priyanka-surana )

2022-02-17 13:29 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +    samtools view -h ${prefix}.bam | filter_five_end.pl | samtools view -Sb -> ${prefix}_filtered.bam
To make it consistent with the other module:
- Add `$args` to allow customisation
- Allow multi-threading
- Use `-o` for the output file

```suggestion
    samtools view -h ${prefix}.bam | filter_five_end.pl | samtools view -Sb $args -@ $task.cpus -o ${prefix}_filtered.bam -
```

2022-02-17 14:54 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +    if (meta.single_end) {
@priyanka-surana . I had a discussion with Cibin and he reminded me that you both had discussed this at a meeting, and you had shown that some existing nf-core modules have this `if (meta.single_end)` construct. So I guess it's fine as it is ?

2022-02-17 14:56 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +
(trailing whitespace flagged by the linter)
```suggestion

```

2022-02-22 17:21 UTC, muffato commented
Can you please fix the indentation on the yaml files (yours, not the ones under `~/.github`) ?

2022-02-25 13:02 UTC, muffato commented on modules/arima/filterfiveend/main.nf
> +    container "gitlab-registry.internal.sanger.ac.uk/tol-it/arima:${version}"
Let's wait for @gq1 to push this image to quay.io, and update this reference here. Then, the CI should run and 🤞🏼 pass

2022-02-25 13:02 UTC, muffato commented on modules/arima/filterfiveend/meta.yml
> +description: Filter BAM files using Arima Filter five end
```suggestion
description: Filter BAM files using Arima filter_five_end.pl
```

2022-02-25 13:02 UTC, muffato commented on modules/arima/filterfiveend/meta.yml
> +  - filter
```suggestion
  - bam
  - filter
```

2022-02-25 13:02 UTC, muffato commented on tests/modules/arima/filterfiveend/test.yml
> +    - path: /tmp/tmpfozjoqfr/arima/test_filtered.bam
I just noticed this: the `/tmp/*` paths are specific to that run of the module and will be different every time else. Use `output/` instead

2022-02-28 11:24 UTC, cibinsb commented on modules/arima/filterfiveend/main.nf
> +    if (meta.single_end) {
Done.

2022-02-28 12:57 UTC, muffato commented
I'm pretty sure there were some md5 checksums in the test yml file, but I can't see those any more

2022-03-09 21:44 UTC, muffato approved these changes

2022-03-09 21:44 UTC, merged