Purgedups
sanger-tol/nf-core-modules pull request #7
Opened 2022-04-29 13:09 UTC by yumisims

## PR checklist

Closes #XXX 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the module conventions in the [contribution docs](https://github.com/nf-core/modules/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, include test data in your PR.
- [ ] Remove all TODO statements.
- [ ] Emit the `versions.yml` file.
- [ ] Follow the naming conventions.
- [ ] Follow the parameters requirements.
- [ ] Follow the input/output options guidelines.
- [ ] Add a resource `label`
- [ ] Use BioConda and BioContainers if possible to fulfil software requirements.
- Ensure that the test works with either Docker / Singularity. Conda CI tests can be quite flaky:
  - [ ] `PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=singularity pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`
  - [ ] `PROFILE=conda pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware`

2022-05-04 09:25 UTC, muffato requested changes
Also, the name of the module is meant to reflect the software package and tool name, not the pipeline. Here, the module is only for the FastK command of the FastK package, so the directory should be `modules/fastk/fastk`, leaving room for other FastK commands such as `Fastmerge`

2022-05-11 10:45 UTC, muffato reviewed
1. I've made a slight modification to the Dockerfile to record the commit IDs that were used (since FastK is not properly versioned): https://gitlab.internal.sanger.ac.uk/tol-it/software/docker-images/-/merge_requests/5/diffs?commit_id=965adf60a693d8953018d2967ac479244602b9b3
The commit IDs are recorded in `/usr/local/src/*.version`. This bumps up the container version here
2. We now have the S3 bucket to host the test data, cf the README and the config file at https://github.com/sanger-tol/nf-core-modules/tree/test_data/tests/config
I have added your data

2022-05-11 10:45 UTC, muffato commented on tests/modules/purgedups/fastk/main.nf
> +           file('/lustre/scratch123/tol/teams/grit/yy5/nf_test_small/ilDiaRubi1.trimmedReads.fasta.gz', checkIfExists: true),
```suggestion
           file('https://tolit.cog.sanger.ac.uk/test-data/Diarsia_rubi/working/ilDiaRubi1.hicanu.20220110/subset/ilDiaRubi1.trimmedReads.fasta.gz', checkIfExists: true),
```

2022-05-16 15:15 UTC, yumisims commented on modules/purgedups/fastk/meta.yml
> +    type:
deleted

2022-05-16 15:37 UTC, yumisims commented on modules/purgedups/fastk/meta.yml
> +      pattern: "*.{bam,cram,sam}"
deleted

2022-05-21 08:55 UTC, gq1 commented
The latest changes being being merged to this branches now. You can delete another merge request.

2022-06-10 12:39 UTC, muffato commented
Hi Yumi.
For review, it's easier if you can make 1 pull request per software, e.g. just fastk here, and do genescope/purgedups in other PRs.

By the way, there is an ongoing pull-request on nf-core for fastk: https://github.com/nf-core/modules/pull/1739/files
It uses a Docker image EBP/Sweden people have built somewhere. I can't find exactly where the Dockerfile is, but it seems to be part of the genomeassembler pipeline they're working on (which should mimic our own), cf https://github.com/NBISweden/Earth-Biogenome-Project-pilot/issues/24

2022-06-10 16:34 UTC, yumisims commented
Hi, I have modified the modules accordingly. 
I am also aware the module name conflicts with the one you mentioned.  The two modules are very smilar but are used for different purposes. Could you please suggest a name for my module to avoid the conflict. Thanks

2022-06-13 09:25 UTC, mahesh-panchal commented
> It uses a Docker image EBP/Sweden people have built somewhere. I can't find exactly where the Dockerfile is

The Dockerfile is currently on another branch as I'm working on something else: https://github.com/NBISweden/Earth-Biogenome-Project-pilot/blob/feature_asm_validation/dockerfiles/fastk_genescopefk_merquryfk.Dockerfile

2022-06-13 09:46 UTC, muffato commented
@yumisims : as far as I can see, the upstream module from @mahesh-panchal does the same thing, so no need to develop one in ToL. Can you instead review it ?

2022-06-13 10:36 UTC, mahesh-panchal commented
I've Histex, GeneScopeFK, and MerquryFK waiting in the wings too.

2022-06-20 16:19 UTC, closed without merging